// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMsegP-oIEEohanHHQWlCBKEFLTOuNR8A',
    appId: '1:783027056900:web:62b515ccb5d80681e3a051',
    messagingSenderId: '783027056900',
    projectId: 'pulsewell-f58a7',
    authDomain: 'pulsewell-f58a7.firebaseapp.com',
    storageBucket: 'pulsewell-f58a7.appspot.com',
    measurementId: 'G-9HGB11RTHW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-c31guQvEtutqSOe2wPDheuh0Ps9Dfro',
    appId: '1:783027056900:android:001f1250c0c31fc3e3a051',
    messagingSenderId: '783027056900',
    projectId: 'pulsewell-f58a7',
    storageBucket: 'pulsewell-f58a7.appspot.com',
  );
}
